### ISSUE TITLE
“发展”，“优化”等词被分开？

### ISSUE THREAD

**Issue by crapthings** [bluelovers/node-segment#2]
```
// 载入模块
var Segment = require('novel-segment');
// 创建实例
var segment = new Segment();
// 使用默认的识别模块及字典，载入字典文件需要1秒，仅初始化时执行一次即可
segment.useDefault();

// 开始分词
console.log(segment.doSegment('为了统一知识产权案件裁判标准，进一步加强知识产权司法保护，优化科技创新法治环境，加快实施创新驱动发展战略，特作如下决定：一、当事人对发明专利、实用新型专利、植物新品种、集成电路布图设计、技术秘密、计算机软件、垄断等专业技术性较强的知识产权民事案件第一审判决、裁定不服，提起上诉的，由最高人民法院审理。'));
```

https://npm.runkit.com/novel-segment

**Comment by crapthings** [comment]
![image](https://user-images.githubusercontent.com/1147704/47692261-08dc5b00-dc30-11e8-8a8a-f48de996096b.png)

**Comment by bluelovers** [comment]
@crapthings 現在有更新的字典是以預設使用者已經手動設定 `autoCjk: true` 來修改的

```ts
const segment = new Segment({
		autoCjk: true
	}); 
```

開啟這個選項之後
會自動將將字典檔內的資料同時支援 簡體 繁體 字(包含混雜使用)

但是缺點也是因為自動轉換
所以導致字典載入的時間會加長

而必須要使用 cache 才能稍微縮短載入時間
https://github.com/bluelovers/node-segment/blob/master/test/lib/index.ts

又或者只需要簡體的話
可以將字典內的繁體部份去轉簡

然後額外去載入該字典來補充

---

因為我是使用繁體輸入法
並且沒有特地去轉簡

所以有些字典在我修改之後 會變成 繁體字

因此如果沒有開啟這個選項的話
就會導致部分常見字詞會沒有成功判斷到

![default](https://user-images.githubusercontent.com/167966/47699315-6c28b600-dc4d-11e8-9804-a9a1265abfb3.png)

**Comment by crapthings** [comment]
哦哦 cool (* ￣3)(ε￣ *)啵啵

**Comment by bluelovers** [comment]
另外出現的結果當中的 s: true 代表這個詞 是本身就存在於字典內

s: undefined 則代表 這個詞 是透過自動繁簡處理之後 才辨識到的
