### ISSUE TITLE
输出 unified AST

### ISSUE THREAD

**Issue by linonetwo** [bluelovers/node-segment#4]
如果支持 [nlcst](https://github.com/syntax-tree/nlcst) 的话，就可以把这个库用在 [nlp-pattern-match](https://github.com/azu/nlp-pattern-match) 里面了。

我本来打算用我改的那个 [segmentit](https://github.com/linonetwo/segmentit) 来改，但我觉得你的这个库更用心，分词算法和词典都有改进，在你的这个库的基础上加入 NLCST 支持可能更好。

**Comment by linonetwo** [comment]
目前这个库只能输出 POS tag，你知道怎么修改才能输出 dependency tree 吗？

**Comment by bluelovers** [comment]
@linonetwo 
你有對應到 nlcst 後的中文結構範例嗎?

**Comment by linonetwo** [comment]
好像不需要在这边直接转换为 NLCST 格式，我应该会写一个 `nlcst-parse-chinese` 来转换。

[日文的长这样](https://github.com/azu/nlp-pattern-match/blob/master/packages/nlcst-parse-japanese/README.md#usage)，它好像只表示了 段落-句子-词 这样简单的 CST，而不是依存语法树。

如果需要先构建依存语法树的话那才应该在这边构建，我先问问是不是需要构建依存语法树吧 https://github.com/azu/nlp-pattern-match/issues/8
不过依存语法树好像没法用现在的字典构建出来。
